import type { RecommendationPrivateReportArtifactModelV2 } from "@/report/artifact-model";

export function PublicSourceForensicsReportArtifact({ model }: { model: RecommendationPrivateReportArtifactModelV2 }) {
  const report=model.recommendationReport, zh=model.locale==="zh";
  return <main className="recommendation-artifact public-source-artifact">
    <nav className="artifact-actions no-print" aria-label="Report formats"><a href={`/reports/${model.reportId}/recommendation-report.html`}>HTML</a><a className="primary" href={`/api/reports/${model.reportId}/artifacts/recommendation-report.pdf`}>PDF</a></nav>
    <header className="cover forensic-cover artifact-section"><p className="eyebrow">OPEN GEO CONSOLE · {zh?"公开来源取证报告":"PUBLIC-SOURCE FORENSICS REPORT"}</p><h1>{report.websiteFoundationAppendix.organizationProfile.organizationName??report.targetUrl}</h1><p className="verdict-copy">{report.executiveVerdict.text}</p><dl className="cover-meta"><div><dt>URL</dt><dd>{report.targetUrl}</dd></div><div><dt>{zh?"覆盖":"Coverage"}</dt><dd>{report.coverage.status} · {report.coverage.completedQueryCount}/{report.coverage.expectedQueryCount}</dd></div><div><dt>{zh?"证据截止":"Evidence cutoff"}</dt><dd>{report.evidenceCutoffAt}</dd></div></dl></header>
    <Section number="01" title={zh?"买方问题与公开搜索范围":"Buyer questions and public-search scope"}><ol className="question-list">{report.questions.questions.map((q)=><li key={q.id}><strong>{q.exactText}</strong><p>{q.derivation.subject} · {q.kind}</p></li>)}</ol><p>{zh?"公开搜索结果顺序仅作为原始方法上下文，不代表 AI 排名。":"Public-search order is raw methodology context only; it is not an AI ranking."}</p></Section>
    <Section number="02" title={zh?"客户与公开来源对照":"Customer and public-source comparison"}>{report.customerComparison.map((item)=><article className="gap-row" key={item.id}><h3>{item.title}</h3><p>{item.text}</p><EvidenceRefs evidence={item.evidenceIds} findings={item.websiteFindingIds}/></article>)}</Section>
    <Section number="03" title={zh?"可核验证据图谱":"Verifiable public-source evidence graph"}><p>{report.sourceGraph.evidence.length} {zh?"条证据":"evidence records"} · {report.sourceGraph.entities.length} {zh?"个实体":"entities"} · {report.sourceGraph.claims.length} {zh?"项声明":"claims"}</p><div className="citation-list">{report.sourceGraph.evidence.map((e)=><article className="citation-row" key={e.evidenceId}><div className="grade-mark">{e.grade}</div><div><p className="citation-category">{e.ownershipCategory} · {e.registrableDomain}</p><h3><a href={e.canonicalUrl}>{e.canonicalUrl}</a></h3><p>{e.verifiedExcerpt??(zh?"无可保留摘录":"No retained excerpt")}</p><small>{e.observationRefs.length} observation(s) · {e.evidenceFamilyId}</small></div></article>)}</div></Section>
    <Section number="04" title={zh?"三项优先行动":"Three priorities"}><div className="priority-grid">{report.executivePriorities.map((p,index)=><article key={p.id}><span>0{index+1}</span><h3>{p.title}</h3><p>{p.text}</p><EvidenceRefs evidence={p.evidenceIds} findings={p.websiteFindingIds}/></article>)}</div></Section>
    <Section number="05" title={zh?"供应商任务包":"Vendor task package"}>{report.vendorTaskPackage.tasks.map((task)=><article className="vendor-task" key={task.id}><p className="citation-category">{task.vendor}</p><h3>{task.title}</h3><p>{task.text}</p><div className="vendor-columns"><div><h4>{zh?"动作":"Actions"}</h4><ul>{task.actions.map((x)=><li key={x}>{x}</li>)}</ul></div><div><h4>{zh?"验收标准":"Acceptance criteria"}</h4><ul>{task.acceptanceCriteria.map((x)=><li key={x}>{x}</li>)}</ul></div></div><EvidenceRefs evidence={task.evidenceIds} findings={task.websiteFindingIds}/></article>)}</Section>
    <Section number="06" title={zh?"网站基础附录":"Website foundation appendix"}><p>{report.websiteFoundationAppendix.executiveSummary.overview}</p><div className="foundation-scores">{report.websiteFoundationAppendix.dimensionScores.map((s)=><article key={s.dimension}><strong>{s.score}/100</strong><h3>{s.dimension}</h3><p>{s.explanation}</p></article>)}</div><p><strong>{zh?"确定性技术分数":"Deterministic technical score"}: {model.technicalReport.score}/100</strong></p></Section>
    <Section number="07" title={zh?"方法、来源与限制":"Methodology, provenance, and limitations"}><dl className="provenance-grid"><div><dt>{zh?"搜索表面":"Search surface"}</dt><dd>{report.authority.surface.surfaceId} / {report.authority.surface.surfaceVersion}</dd></div><div><dt>{zh?"快照":"Snapshots"}</dt><dd>{report.snapshotRefs.length} · {report.customerCostDisclosure.freshness} · {report.customerCostDisclosure.collectedNewObservation?"new observation":"reused observation"}</dd></div><div><dt>{zh?"生成方式":"Synthesis"}</dt><dd>{report.synthesisProvenance.mode}</dd></div></dl><ul>{report.limitations.map((x)=><li key={x}>{x}</li>)}</ul></Section>
  </main>;
}
function Section({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="artifact-section"><div className="section-heading"><span>{number}</span><h2>{title}</h2></div>{children}</section>;}
function EvidenceRefs({evidence,findings}:{evidence:readonly string[];findings:readonly string[]}){return <p className="evidence-refs"><strong>Evidence:</strong> [{evidence.join(", ")||"none"}] · <strong>Website:</strong> [{findings.join(", ")||"none"}]</p>;}
