import {createHash,createHmac,timingSafeEqual} from "node:crypto";
import {parsePublicSearchSurface,type PublicSearchSurface,type SearchExecutionBudget} from "@open-geo-console/public-search-observer";
export interface PublicSearchCertificationSigningConfig{secret:string;keyId:string;version:"v1";}
export interface PublicSearchCertificationArtifact{version:1;mode:"live"|"fixture";installable:boolean;environment:"protected_staging"|"production";adapterId:string;surface:PublicSearchSurface;supportedLocales:string[];supportedRegions:string[];termsReviewReference:string;commercialUseReviewReference:string;storageDisplayReviewReference:string;provenanceSemantics:string;errorSemantics:string;budget:SearchExecutionBudget;reviewedBy:string;reviewedAt:string;artifactHash:string;signature:{algorithm:"hmac-sha256";keyId:string;version:"v1";value:string}|null;}
type Content=Omit<PublicSearchCertificationArtifact,"artifactHash"|"signature">;
export function readPublicSearchCertificationSigningConfig(environment:NodeJS.ProcessEnv):PublicSearchCertificationSigningConfig{const secret=environment.OGC_PUBLIC_SEARCH_CERTIFICATION_SIGNING_SECRET?.trim(),keyId=environment.OGC_PUBLIC_SEARCH_CERTIFICATION_SIGNING_KEY_ID?.trim(),version=environment.OGC_PUBLIC_SEARCH_CERTIFICATION_SIGNING_VERSION?.trim();if(!secret||!keyId||!version)throw new Error("Public-search certification signing configuration is incomplete.");if(Buffer.byteLength(secret)<32)throw new Error("Public-search certification signing secret must contain at least 32 bytes.");for(const candidate of [environment.OGC_AI_API_KEY,environment.OGC_TOKEN_HASH_SECRET,environment.OGC_PUBLIC_SEARCH_RUNTIME_SECRET])if(candidate?.trim()===secret)throw new Error("Public-search certification signing secret must be independent from runtime credentials.");if(!/^[A-Za-z0-9._-]{1,64}$/.test(keyId)||version!=="v1")throw new Error("Public-search certification signing key identity is invalid.");return {secret,keyId,version};}
export function finalizePublicSearchCertificationArtifact(input:Content,signing?:PublicSearchCertificationSigningConfig):PublicSearchCertificationArtifact{const content={...input,surface:parsePublicSearchSurface(input.surface),supportedLocales:unique(input.supportedLocales),supportedRegions:unique(input.supportedRegions),budget:budget(input.budget)};validate(content);if(content.mode==="live"&&content.installable&&!signing)throw new Error("Installable live public-search certification requires signing configuration.");const artifactHash=sha(stable(content)),signed=content.mode==="live"&&content.installable&&signing;return {...content,artifactHash,signature:signed?{algorithm:"hmac-sha256",keyId:signing.keyId,version:"v1",value:signature(artifactHash,signing)}:null};}
export function parsePublicSearchCertificationArtifact(value:unknown,signing?:PublicSearchCertificationSigningConfig):PublicSearchCertificationArtifact{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Public-search certification artifact is invalid.");const raw=value as PublicSearchCertificationArtifact,{artifactHash,signature:rawSignature,...content}=raw,parsed=finalizePublicSearchCertificationArtifact(content,raw.mode==="live"&&raw.installable?signing:undefined);if(!hash(artifactHash)||artifactHash!==parsed.artifactHash)throw new Error("Public-search certification artifact hash mismatch.");if(raw.mode==="live"&&raw.installable){if(!signing||!rawSignature||rawSignature.keyId!==signing.keyId||rawSignature.version!==signing.version||rawSignature.algorithm!=="hmac-sha256"||!safe(rawSignature.value,signature(artifactHash,signing)))throw new Error("Public-search certification artifact signature is invalid.");}else if(rawSignature!==null)throw new Error("Fixture or non-installable artifacts cannot carry a signature.");return parsed;}
export function assertInstallablePublicSearchCertificationArtifact(artifact:PublicSearchCertificationArtifact):void{if(artifact.mode!=="live"||!artifact.installable||!artifact.signature||artifact.environment!=="protected_staging")throw new Error("Only signed live protected-staging public-search artifacts are installable.");}
function validate(value:Content){if(value.version!==1||!value.adapterId.trim()||!Number.isFinite(Date.parse(value.reviewedAt))||!value.reviewedBy.trim())throw new Error("Public-search certification metadata is invalid.");if(value.mode==="fixture"&&value.installable)throw new Error("Fixture certification is never installable.");for(const field of [value.termsReviewReference,value.commercialUseReviewReference,value.storageDisplayReviewReference,value.provenanceSemantics,value.errorSemantics])if(!field.trim())throw new Error("Public-search certification review evidence is incomplete.");if(!value.supportedLocales.includes(value.surface.locale)||!value.supportedRegions.includes(value.surface.region))throw new Error("Public-search certification capability mismatch.");}
function budget(value:SearchExecutionBudget):SearchExecutionBudget{for(const [key,item] of Object.entries(value))if(!Number.isSafeInteger(item)||item<0)throw new Error(`Public-search certification budget ${key} is invalid.`);if(value.maxRequests<1||value.maxResults<1||value.timeoutMs<1)return fail("Public-search certification budget cannot disable execution.");return {...value};}
function unique(values:string[]){if(!Array.isArray(values)||!values.length||values.some((x)=>typeof x!=="string"||!x.trim())||new Set(values).size!==values.length)throw new Error("Public-search certification capabilities are invalid.");return [...values].sort();}
function signature(artifactHash:string,config:PublicSearchCertificationSigningConfig){return createHmac("sha256",config.secret).update(`ogc-public-search-certification\0${config.version}\0${config.keyId}\0${artifactHash}`).digest("hex");}
function safe(actual:string,expected:string){if(!hash(actual))return false;const a=Buffer.from(actual,"hex"),e=Buffer.from(expected,"hex");return a.length===e.length&&timingSafeEqual(a,e);}function hash(value:unknown):value is string{return typeof value==="string"&&/^[a-f0-9]{64}$/.test(value);}function sha(value:string){return createHash("sha256").update(value).digest("hex");}function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;return JSON.stringify(value);}function fail(message:string):never{throw new Error(message);}
